# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-09 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inapp_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercampaign',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaigncustomparam',
            name='param_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='campaigncustomparam',
            name='param_value',
            field=models.CharField(max_length=1000),
        ),
    ]
